export {
  discoverTraeRoot,
  getDefaultTraeUserDataPaths,
  requireTraeRoot,
  type DiscoveredTraeRoot,
  type TraePlatform,
  type TraeProduct,
  type TraeRootAvailability,
  type TraeRootDiscoveryOptions,
  type TraeRootSource,
} from "./path-discovery.js";
export {
  normalizeWorkspaceFileUri,
  resolveTraeWorkspaces,
  resolveWorkspaceLocation,
  type ParsedWorkspaceLocation,
  type ProjectPathSource,
  type ResolvedProjectPath,
  type ResolvedTraeWorkspace,
  type WorkspaceLocation,
  type WorkspaceLocationKind,
  type WorkspaceResolutionIssue,
  type WorkspaceResolutionIssueCode,
  type WorkspaceResolutionOptions,
  type WorkspaceResolutionReport,
} from "./workspace-resolution.js";
export {
  createReadonlySqliteSnapshot,
  withReadonlySqliteSnapshot,
  type ReadonlySqliteSnapshot,
  type SqliteSnapshotOptions,
} from "./sqlite-snapshot.js";
export {
  probeTraeCapabilities,
  VERIFIED_TRAE_CAPABILITY_VERSION,
  type CapabilityCount,
  type CapabilityEvidence,
  type CapabilityField,
  type CapabilityProbeIssue,
  type CapabilityStatus,
  type CapabilityVerification,
  type RuntimeCapability,
  type RuntimeCapabilityFieldId,
  type TraeCapabilityProbeOptions,
  type TraeCapabilityReport,
  type TraeStorageProfileId,
  type WorkspaceCapability,
  type WorkspaceCapabilityFieldId,
  type WorkspaceStorageProfile,
} from "./capability-probe.js";
