export {
  discoverTraeRoot,
  getDefaultTraeUserDataPaths,
  requireTraeRoot,
  type DiscoveredTraeRoot,
  type TraePlatform,
  type TraeProduct,
  type TraeRootAvailability,
  type TraeRootDiscoveryOptions,
  type TraeRootSource,
} from "./path-discovery.js";
export {
  normalizeWorkspaceFileUri,
  resolveTraeWorkspaces,
  resolveWorkspaceLocation,
  type ParsedWorkspaceLocation,
  type ProjectPathSource,
  type ResolvedProjectPath,
  type ResolvedTraeWorkspace,
  type WorkspaceLocation,
  type WorkspaceLocationKind,
  type WorkspaceResolutionIssue,
  type WorkspaceResolutionIssueCode,
  type WorkspaceResolutionOptions,
  type WorkspaceResolutionReport,
} from "./workspace-resolution.js";
