export {
  discoverTraeRoot,
  getDefaultTraeUserDataPaths,
  requireTraeRoot,
  type DiscoveredTraeRoot,
  type TraePlatform,
  type TraeProduct,
  type TraeRootAvailability,
  type TraeRootDiscoveryOptions,
  type TraeRootSource,
} from "./path-discovery.js";
export {
  normalizeWorkspaceFileUri,
  resolveTraeWorkspaces,
  resolveWorkspaceLocation,
  type ParsedWorkspaceLocation,
  type ProjectPathSource,
  type ResolvedProjectPath,
  type ResolvedTraeWorkspace,
  type WorkspaceLocation,
  type WorkspaceLocationKind,
  type WorkspaceResolutionIssue,
  type WorkspaceResolutionIssueCode,
  type WorkspaceResolutionOptions,
  type WorkspaceResolutionReport,
} from "./workspace-resolution.js";
export {
  createReadonlySqliteSnapshot,
  withReadonlySqliteSnapshot,
  type ReadonlySqliteSnapshot,
  type SqliteSnapshotOptions,
} from "./sqlite-snapshot.js";
export {
  probeTraeCapabilities,
  VERIFIED_TRAE_CAPABILITY_VERSION,
  type CapabilityCount,
  type CapabilityEvidence,
  type CapabilityField,
  type CapabilityProbeIssue,
  type CapabilityStatus,
  type CapabilityVerification,
  type RuntimeCapability,
  type RuntimeCapabilityFieldId,
  type TraeCapabilityProbeOptions,
  type TraeCapabilityReport,
  type TraeStorageProfileId,
  type WorkspaceCapability,
  type WorkspaceCapabilityFieldId,
  type WorkspaceStorageProfile,
} from "./capability-probe.js";
export {
  assessTraeSessionRecoverability,
  gradeSessionRecoveries,
  gradeSessionRecovery,
  type MessageSourceStatus,
  type RecoveryReason,
  type RecoveryReasonCode,
  type SessionEvidenceContext,
  type SessionEvidenceProvider,
  type SessionMessageEvidence,
  type SessionRecoveryAssessment,
  type SessionRecoveryEvidence,
  type SessionRecoveryIssue,
  type TraeSessionRecoveryOptions,
  type TraeSessionRecoveryReport,
} from "./recovery-grading.js";
export {
  parseTraeRuntimeSessionMetadata,
  readTraeSessionMetadata,
  VERIFIED_TRAE_SESSION_METADATA_VERSION,
  type ReadTraeSessionMetadataOptions,
  type TraeRuntimeSessionMetadataProvider,
  type TraeRuntimeSessionMetadataRequest,
  type TraeSessionMetadata,
  type TraeSessionMetadataIssue,
  type TraeSessionMetadataIssueCode,
  type TraeSessionMetadataReport,
  type TraeSessionMetadataSource,
  type TraeSessionMetadataSourceKind,
  type TraeSessionMetadataStatus,
} from "./session-metadata.js";
export {
  parseTraeQueryCache,
  parseTraeRuntimeUserMessages,
  readTraeUserMessages,
  VERIFIED_TRAE_USER_MESSAGE_VERSION,
  type ReadTraeUserMessagesOptions,
  type TraeQueryCacheEntry,
  type TraeQueryCacheFile,
  type TraeQueryCacheMultimedia,
  type TraeRuntimeUserMessageProvider,
  type TraeRuntimeUserMessageRequest,
  type TraeUserMessage,
  type TraeUserMessageFieldSource,
  type TraeUserMessageIssue,
  type TraeUserMessageIssueCode,
  type TraeUserMessageReport,
  type TraeUserMessageSource,
  type TraeUserMessageSourceKind,
} from "./user-messages.js";
export {
  parseTraeRuntimeAssistantMessages,
  readTraeAssistantMessages,
  scanTraeLongTextResources,
  VERIFIED_TRAE_ASSISTANT_MESSAGE_VERSION,
  type ReadTraeAssistantMessagesOptions,
  type TraeAssistantMessage,
  type TraeAssistantMessageIssue,
  type TraeAssistantMessageIssueCode,
  type TraeAssistantMessageReport,
  type TraeAssistantMessageSource,
  type TraeAssistantMessageSourceKind,
  type TraeAssistantMessageStatus,
  type TraeAssistantText,
  type TraeAssistantTextSource,
  type TraeLongTextReference,
  type TraeLongTextResource,
  type TraeRuntimeAssistantMessageProvider,
  type TraeRuntimeAssistantMessageRequest,
} from "./assistant-messages.js";
